version: "2"
run:
  go: "1.24"
linters:
  default: all
  disable:
    - godot
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - gomoddirectives
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - mnd
    - prealloc
    - predeclared
    - tagliatelle
    - varnamelen
  settings:
    importas:
      alias:
        - pkg: github.com/pkg/errors   # full module path
          alias: pkgerrors             # the only allowed alias
      no-unaliased: true               # forbid a bare  `import "github.com/pkg/errors"`
    wrapcheck:
      ignore-sigs:
        - ".Wrap("     # the ONLY helper considered a wrapper
      extra-ignore-sigs:
        - "errors.New("
    exhaustive:
      default-signifies-exhaustive: true
    govet:
      enable-all: true
    misspell:
      locale: US
    nlreturn:
      block-size: 2
    nolintlint:
      require-specific: true
      allow-unused: true
    revive:
      severity: warning
      enable-all-rules: true
      rules:
        - name: get-return # HTTP functions can be named "Get..." but not return anything
          disabled: true
        - name: add-constant
          disabled: true
        - name: file-header
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: function-length
          disabled: true
        - name: argument-limit
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
        - name: max-control-nesting
          arguments:
            - 10
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - contextcheck
          - dupl
          - forcetypeassert
          - gosec
          - maintidx
          - perfsprint
          - revive
          - wrapcheck
        path: (.*)(_test|scripts)(.*)
      - path: (.+)\.go$
        text: 'shadow: declaration of'
      - path: (.+)\.go$
        text: shadows an import name
      - path: (.+)\.go$
        text: 'nested-structs: no nested structs are allowed'
      - path: (.+)\.go$
        text: confusing-naming
      - path: (.+)\.go$
        text: flag-parameter
      - path: (.+)\.go$
        text: 'G306: Expect WriteFile permissions to be 0600 or less'
      - path: (.+)\.go$
        text: 'G601: Implicit memory aliasing in for loop'
      - path: (.+)\.go$
        text: 'loopclosure: loop variable'
      - path: (.+)\.go$
        text: Range statement for test
      - path: (.+)\.go$
        text: 'range-val-address: suspicious assignment of'
      - path: (.+)\.go$
        text: exporting a pointer for the loop variable snapshot
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  fix: false
