version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./.env:/app/.env:ro"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
